#!/bin/gnuplot -persist
set terminal x11
set size square
set style line 1 lc rgb '#0060ad' lt 1 lw 2 pt 7 ps 1   # --- blue
set style line 2 lc rgb '#8F1500' lt 1 lw 2 pt 7 ps 1   # --- red
set style line 3 lc rgb '#108902' lt 1 lw 2 pt 7 ps 1   # --- dark green

plot 'Evolution.dat' skip 1 using 1:2 with linespoints ls 1 t "Body 1", '' skip 1 using 4:5 with linespoints ls 2 t "Body 2", '' skip 1 using 7:8 with linespoints ls 3 t "Body 3"
exit