#!/bin/gnuplot -persist
set terminal x11
set size square
set xrange [-2e11:2e11]
set yrange [-2e11:2e11]
set style line 1 lc rgb '#0060ad' lt 1 lw 2 pt 7 ps 1   # --- blue
set style line 2 lc rgb '#808080' lt 1 lw 2 pt 7 ps 0.75   # --- grey
set style line 3 lc rgb '#FFFF00' lt 1 lw 2 pt 7 ps 2   # --- yellow

plot 'Evolution.dat' skip 1 using 1:2 with linespoints ls 1 t "Earth", '' skip 1 using 4:5 with linespoints ls 3 t "Sun", '' skip 1 using 7:8 with linespoints ls 2 t "The Moon"
exit